### ISSUE TITLE
Publisher / Subscriber 구현 언어 결정 

### ISSUE THREAD

**Issue by wolfses** [wolfses/URQA-Server#4]
RabbitMQ의 Publisher / Subscriber 를 구현하는데 어떤언어로 하는것이 좋을까요.

현재 UrQA서버는 모두 Python(django)로 구성되어있습니다.

구성을 변경하는 이 시점에서 

확장성, 유지보수, 기타등등을 고려하여 하나의 언어를 지정하고자 합니다.

의견 부탁드립니다.

**Comment by EastComplete** [comment]
난 시간이나 여러가지 비용때문에, python으로 했는데..   

난 java 형님을 살짝 추천..  아마 다양한 생태계를 가진 java라서 추후..  여러 확장 포인트를 볼때..  그냥 의견..

**Comment by pegasuskim** [comment]
일단 재 생각은 서버쪽은(Publisher) nodejs 가면 어떨까 싶습니다.
worker 쪽, 그러니까 Data Provider ( Subscriber ) 쪽은 python 으로..

nodejs  적용하고자 하는 이유는 일단 초당 처리 Request 가 약 9000 건으로 처리속도가 상당히 빠르고 클러스터링를 지원 하고 있습니다.(현재 만들어 놓은 nodejs 역시 클러스터링을 적용 해 놓았습니다), 차후 배포나 확장성 면에서도 상당히 용의 할것으로 보여 집니다.

worker 쪽은 backend에서 처리 하는 거라 처리속도 보다는 데이토 신뢰성 위주로 가야 합니다.
기존에 python 으로 잘 구조화 되어 있어서 그걸 활용 하면 되지 않을까 싶습니다

**Comment by yunhoi129** [comment]
엇... 구글링하다가 들어왔는데.. ㅋㅋ 반가운 얼굴들이 있네요 ㅎㅎ
p.s 쓸모없는 코멘트라 죄송합니다... :)

**Comment by EastComplete** [comment]
java로 가는 것으로 결정하고 닫습니다.
