### ISSUE TITLE
github 팀을 만든다음 그 산하로 프로젝트 이전.. 

### ISSUE THREAD

**Issue by EastComplete** [wolfses/URQA-Server#5]
현재 @wolfses 의 개인 계정에 프로젝트가 속해 있는데.
일전에 진성주가 준 가이드 처럼. 팀 . org를 만들어서.. 

그 쪽에 작업을 하는게 어떨까요.? 그게 향후 오픈소스로 관리하기에도 좋을거 같습니다.

**Comment by pegasuskim** [comment]
네 저도 같은 생각 입니다. ^^

**Comment by wolfses** [comment]
혹시 깃헙자체에서 팀을 지원하는 서비스가있는가요 아니면

아이디를 새로 만들어서 이름만 팀명으로 하면 되는건가요? 알아보니 딱히 팀을 지원하는게 없는거같기두 하고..

아 찾았습니다.

**Comment by wolfses** [comment]
https://github.com/organizations/UrQA

이쪽으로 이전하였습니다.

커밋도 이제 이쪽으로해주시면 좋겠습니다.
